CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(254) NOT NULL,
    login    VARCHAR(64)  NOT NULL,
    name     VARCHAR(100),
    birthday DATE
);

CREATE TABLE IF NOT EXISTS genres
(
    id   INTEGER PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS mpa_ratings
(
    id   INTEGER PRIMARY KEY,
    name VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS films
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    description   VARCHAR(200),
    release_date  DATE         NOT NULL,
    duration      INTEGER      NOT NULL,
    mpa_rating_id INTEGER,

    CONSTRAINT positive_duration CHECK (duration > 0),
    CONSTRAINT valid_release_date CHECK (release_date >= DATE '1895-12-28'),

    CONSTRAINT fk_films_mpa_rating
        FOREIGN KEY (mpa_rating_id) REFERENCES mpa_ratings (id)
);

CREATE TABLE IF NOT EXISTS friend_requests
(
    requester_id BIGINT NOT NULL,
    recipient_id BIGINT NOT NULL,

    CONSTRAINT pk_friend_requests PRIMARY KEY (requester_id, recipient_id),
    CONSTRAINT no_self_friend_request CHECK (requester_id <> recipient_id),

    CONSTRAINT fk_friend_requests_requester
        FOREIGN KEY (requester_id) REFERENCES users (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_friend_requests_recipient
        FOREIGN KEY (recipient_id) REFERENCES users (id)
            ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_friend_requests_recipient_id
    ON friend_requests (recipient_id);

CREATE TABLE IF NOT EXISTS friendships
(
    first_id  BIGINT NOT NULL,
    second_id BIGINT NOT NULL,

    CONSTRAINT pk_friendships PRIMARY KEY (first_id, second_id),
    CONSTRAINT normalized_friendship_pair CHECK (first_id < second_id),

    CONSTRAINT fk_friendships_first
        FOREIGN KEY (first_id) REFERENCES users (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_friendships_second
        FOREIGN KEY (second_id) REFERENCES users (id)
            ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_friendships_second_id
    ON friendships (second_id);

CREATE TABLE IF NOT EXISTS film_likes
(
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,

    CONSTRAINT pk_film_likes PRIMARY KEY (film_id, user_id),

    CONSTRAINT fk_film_likes_film
        FOREIGN KEY (film_id) REFERENCES films (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_film_likes_user
        FOREIGN KEY (user_id) REFERENCES users (id)
            ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_film_likes_user_id
    ON film_likes (user_id);

CREATE TABLE IF NOT EXISTS film_genres
(
    film_id  BIGINT  NOT NULL,
    genre_id INTEGER NOT NULL,

    CONSTRAINT pk_film_genres PRIMARY KEY (film_id, genre_id),

    CONSTRAINT fk_film_genres_film
        FOREIGN KEY (film_id) REFERENCES films (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_film_genres_genre
        FOREIGN KEY (genre_id) REFERENCES genres (id)
);
